# Generated by Django 4.0.3 on 2022-04-24 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BestBuySearch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='products',
            field=models.ManyToManyField(to='BestBuySearch.vendorproduct'),
        ),
    ]
