# Generated by Django 4.0.3 on 2022-04-25 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BestBuySearch', '0002_customer_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorproduct',
            old_name='prod_type',
            new_name='item_type',
        ),
        migrations.AlterField(
            model_name='vendorproduct',
            name='payment_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'in-full'), (2, 'monthly')], default=1),
        ),
    ]
