# Generated by Django 4.0.3 on 2022-04-25 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BestBuySearch', '0003_rename_prod_type_vendorproduct_item_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorproduct',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'TV & Home Theater'), (2, 'Audio'), (3, 'Musical Instruments'), (4, 'Care Electronics & GPS'), (5, 'Cameras, Camcorders & Drone'), (6, 'Computers & Tablets'), (7, 'Movies & Music'), (8, 'Video Games'), (9, 'Cell Phones'), (10, 'Appliances'), (11, 'Gift Cards'), (12, 'Name Brands'), (13, 'Baby Care'), (14, 'Services'), (15, 'Health & Wellness'), (16, 'Toys, Games & Collectibles'), (17, 'Smart Home'), (18, 'Sports, Fitness & Recreation'), (19, 'Home, Furniture & Office'), (20, 'Wearable Technology')]),
        ),
        migrations.AlterField(
            model_name='vendorproduct',
            name='item_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'product'), (2, 'service')], default=1),
        ),
        migrations.AlterField(
            model_name='vendorproduct',
            name='payment_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'in full'), (2, 'monthly')], default=1),
        ),
    ]
