# Generated by Django 4.0.3 on 2022-04-25 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BestBuySearch', '0007_vendorproduct_brief_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorproduct',
            name='big_display_image',
            field=models.ImageField(default=2, height_field=700, upload_to='images/', width_field=600),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendorproduct',
            name='small_display_image',
            field=models.ImageField(default=2, height_field=300, upload_to='images/', width_field=450),
            preserve_default=False,
        ),
    ]
