# Generated by Django 4.0.3 on 2022-04-30 17:45

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BestBuySearch', '0013_alter_vendorproduct_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorproduct',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
