# Generated by Django 4.0.3 on 2022-05-03 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BestBuySearch', '0015_alter_vendorproduct_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorproduct',
            name='payment_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'one time payment'), (2, 'monthly'), (3, 'annually')]),
        ),
    ]
