"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 4.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import os
from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY") 

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['sethcram.pythonanywhere.com']


# Application definition

INSTALLED_APPS = [ 
    'BestBuySearch.apps.BestBuySearchConfig', #bc PollsConfig class is in the polls/apps.py file	
    #'django.contrib.admin', #admin site
    'mysite.apps.MyAdminConfig', #admin site replacement
    'django.contrib.auth', #auth syst
    'django.contrib.contenttypes', #content types framework
    'django.contrib.sessions', #sessions framework
    'django.contrib.messages', #messaging framework
    'django.contrib.staticfiles', #static file framework
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

#SITE_URL = '/BestBuySearch/'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

#MySQL:
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'sethcram$bestbuy_RDMS', #name of DB
        'USER': 'sethcram',
        'PASSWORD': config('DB_PASS'), #empty str means rando pass (if not included, defaults to none)
        'HOST': 'sethcram.mysql.pythonanywhere-services.com', #empty str means localhost
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

#myTimeZone: (should be Pacific Time)
TIME_ZONE = 'US/Pacific' 

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'
#STATIC_ROOT = os.path.join(BASE_DIR, "static")
STATIC_ROOT = '/home/sethcram/BestBuySearch/NoMigrations/mysite/static'

# Where user uploaded media is stored (can't be same as static_url)
MEDIA_URL = '/media/'
#MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_ROOT = '/home/sethcram/BestBuySearch/NoMigrations/mysite/media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#only redirects our user-defined login + logout pages
LOGIN_REDIRECT_URL = '/BestBuySearch/products/'
LOGOUT_REDIRECT_URL = '/BestBuySearch/login/'

#Replace default user model
AUTH_USER_MODEL = 'BestBuySearch.User'

LOGIN_URL = 'login'

#avoid transmitting CSRF cookie over HTTTP
CSRF_COOKIE_SECURE = True

#avoid transmitting the session cookie over HTTP accidentally
SESSION_COOKIE_SECURE = True